---
title: "markdown.test"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r pressure, echo=FALSE}
library(dplyr)
library(ggplot2)
library(sf)
library(terra)
library(rnaturalearth)

## mapping objects
# land contours
land <- st_crop(ne_countries(scale = "medium", returnclass = "sf"),
                xmin = -10, xmax = 65, # range for the study area (sf)
                ymin = 55, ymax = 90) |>
  st_transform(# transform to allign with meridian 30
    crs = "+proj=laea +lat_0=75 +lon_0=30 +datum=WGS84 +units=m +no_defs")

# custom theme
theme_custom <- function() {
  theme(
    plot.margin = margin(0, 0, 0, 0),
    legend.position = "right",
    legend.justification = "center",
    legend.margin = margin(0, 0, 0, 0),
    legend.box.margin = margin(0, 0, 0, 0),
    legend.text = element_text(size = 8),
    strip.background = element_rect(fill = "gray", color = "gray45", linewidth = 1),
    plot.title = element_text(size = 20),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 8)
  )
}

save(theme_custom, land, file = "R/mapping_objects.RData")

#
### COMMUNITY DATA CLEANING ----
## load data ranging 2004-2021 (from FISHGLOB_data)
load("data/original/NOR-BTS_clean.RData") 

## data for 2022 (from Laurene Pecouchet)
load("data/original/BESS_data2022.RData")

## unify and filter
nor_full <- data %>% 
  rbind(data2022) %>% # merge                 
  filter(gear %in% c("3270","3271") &  # *   
           latitude > 70 &             # * 
           month %in% c("08", "09"))   # * *ensures to retain only the BES data

length(unique(nor_full$haul_id))      # 3932 hauls
hist(nor_full$haul_dur, breaks = 100) # haul_dur should be ~ 15 minutes
hist(nor_full$depth, breaks = 100)    # continental shelf ends at 500m

nor <- nor_full %>% 
           filter(         
           between(haul_dur, 10, 20) & # exclude large deviations from the 15 minutes
           depth < 500)                # exclude non-shelf areas

length(unique(nor$haul_id)) # 3452 hauls, 480 were lost from filtering

## save filtered community data
save(nor, file = "data/intermediate/NOR-BTS_filtered.RData")

rm(list = setdiff(ls(), "nor")) # cleaning


### BIOMASS EXPLORATION ----

## unique taxa (106)
length(unique(nor$accepted_name))

## total biomass per haul 
total_biomass <- nor %>%    
  group_by(haul_id) %>%
  summarize(total_biomass = sum(wgt_cpua, na.rm = TRUE)) 

## species biomass per haul
species_biomass <- nor %>%  
  group_by(haul_id, accepted_name) %>%
  summarize(biomass = sum(wgt_cpua, na.rm = TRUE)) %>%
  pivot_wider(
    names_from = accepted_name,
    values_from = biomass,
    values_fill = 0  
  )

## most abundant species and fraction of total biomass
top_10 <- nor %>%
  group_by(accepted_name) %>%
  summarize(biomass = sum(wgt_cpua, na.rm = TRUE)) %>%
  arrange(desc(biomass)) %>%
  slice_head(n = 10) %>%
  mutate(fraction = biomass/sum(nor$wgt_cpua, na.rm = TRUE))

sum(top_10$fraction) # together, these 10 account for ~ 90% of the sampled biomass

## merge and keep only top 10 species
biomass <- total_biomass %>%
  left_join(species_biomass, by = "haul_id") %>%
  select(c("haul_id", "total_biomass", top_10$accepted_name)) 

## save
save(biomass, file = "data/intermediate/biomass.RData")

## plotting mean biomass
load("R/mapping_objects.RData")

# data to be used
b_plot_data <- nor %>%
  group_by(haul_id, year, latitude, longitude) %>%
  summarize(depth = median(depth)) %>%
  left_join(biomass, by = "haul_id") %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>%
  st_transform(crs = "+proj=laea +lat_0=75 +lon_0=30 +datum=WGS84 +units=km +no_defs") # Lambert Azimuthal Equal-Area projection centered on study areas

# continuous grid to bin the observations
g <- st_make_grid(b_plot_data,
                  cellsize = 65,
                  what = "polygons",
                  square = TRUE) %>%
  st_sf() 

# spatial join (inner join) to match observations to cells
grid_r <- st_join(g, b_plot_data, left = FALSE) 

# check observation number per cell (ideally = n of years)
cell_counts <- grid_r%>%
  group_by(geometry) %>%
  summarize(n_obs = n(), .groups = "drop")

boxplot(cell_counts$n_obs, horizontal = TRUE) # at 65 km, most of the cells have at least 

prop.table(table((cell_counts$n_obs > 5))) # ~ 80% has more than 5 observations, but 28 have only 1 haul



# responses to plot
res <- c("total_biomass", top_10$accepted_name)

# limits
xlim <- st_bbox(b_plot_data)[c(1, 3)] + c(-65, 65)
ylim <- st_bbox(b_plot_data)[c(2, 4)] + c(-65, 65)

# compute mean values over the time series
for (i in 1:length(res)) { 
  
  grid_mean <- grid_r %>%
    group_by(geometry) %>%
    summarize(x = mean(get(res[i]), na.rm = TRUE)) %>%
    st_as_sf()
  
  max <- round(max(log(grid_mean$x + 1)) * 10)/10
  min <- round(min(log(grid_mean$x + 1)) * 10)/10
  
  p <- ggplot() +
    geom_sf(data = grid_mean, aes(fill = log(x + 1)), color = NA) +
    geom_sf(data = land, fill = "gray45", color = "gray45") +
    scale_x_continuous(limits = xlim) +
    scale_y_continuous(limits = ylim) +
    scale_fill_gradientn(colors = c("darkblue", "white", "darkred"),
                         values = scales::rescale(c(min, max)),
                         limits = c(min, max), 
                         name = "log(kg/km2)",
                         breaks = seq(min, max, length = 3)) + 
    labs(x = "\nLongitude", y = "Latitude\n",
         title = paste0(i - 1, " ", res[i])) + 
    guides(fill = guide_colorbar(barwidth = .5,
                                 barheight = 10,
                                 ticks.linewidth = .1)) +
    theme_custom() 
  
  ggsave(p, file = paste0("doc/biomass_plots/", i - 1, "_mean_", res[i], ".png"),
         width = 15, height = 10, units = "cm")
}

system("which git")

# how many hauls are found in each of these cells?
p <- ggplot() +
  geom_sf(data = cell_counts, fill = "white", color = "black", size = 0.3) +  
  geom_sf(data = land, fill = "gray45", color = "gray45", alpha = 0.3) +  
  geom_sf_text(data = cell_counts, aes(label = n_obs), size = 2, color = "black") +  
  scale_x_continuous(limits = xlim) +
  scale_y_continuous(limits = ylim) +
  labs(
    x = "\nLongitude", y = "Latitude\n",
    title = "Hauls per Grid Cell"
  ) +
  theme_custom() 

ggsave(p, file = paste0("doc/biomass_plots/haul_number.png"),
         width = 15, height = 10, units = "cm")



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
